import type { Metadata } from "next";
import AppNav from "@/components/layout/AppNav";
import type { UserRole } from "@/types/database";
import { getAccessContext } from "@/lib/capabilities/server";
import { PageShell } from "@/components/ui/PageShell";
import { LegalBody, LegalSection, LEGAL_CONTACT } from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Privacy — re:sonate",
  description: "What re:sonate collects about you, why, and what you can ask for.",
};

/**
 * L'informativa, scritta su cio' che il codice fa davvero (verificato il
 * 2026-09-21): profili e ordini su Supabase (eu-west-1, Irlanda), funzioni su
 * Vercel (Dublino), pagamenti su SumUp senza che i dati della carta ci passino,
 * mail via Resend, analytics **solo lato server** su PostHog (nessun cookie di
 * tracciamento, quindi nessun banner), pass Apple Wallet generato su richiesta.
 * La cancellazione dell'account la fa un organizer dall'app su richiesta: non
 * esiste un tasto self-service, e la pagina non lo promette.
 */
export default async function PrivacyPage() {
  // La navigazione, come su ogni pagina pubblica: il wrapper dichiara lo
  // spazio della colonna e `AppNav` e' suo fratello — la forma di
  // `src/app/(public)/events/page.tsx`, letta dal controllo E di
  // `verify:conversion` in QUESTO file. Nessun'altra lettura.
  const { role, capabilities, liveAssignmentCapabilities } = await getAccessContext();
  return (
    <>
    <div className="md:[--nav-inset-inline-start:14rem]">
    <PageShell width="default">
    <LegalBody
      title="Privacy"
      intro="This notice says what we collect when you use re:sonate, why, where it is kept, and what you can ask us to do with it."
    >
      <LegalSection heading="Who is responsible">
        <p>
          The organiser of re:sonate events, reachable at{" "}
          <a href={`mailto:${LEGAL_CONTACT}`} className="inline-flex min-h-11 items-center text-accent">{LEGAL_CONTACT}</a>. Write
          there for anything in this notice.
        </p>
      </LegalSection>

      <LegalSection heading="What we collect, and why">
        <p>
          <strong>When you buy or reserve a ticket:</strong> your name, your email address, what
          you ordered and when, and the payment confirmation from SumUp (a transaction reference,
          never your card details). We need these to issue your tickets, send them to you, let you
          in at the door and handle any refund.
        </p>
        <p>
          <strong>When you have an account:</strong> the same, plus your sign-in details and the
          tickets and drink orders linked to the account. An account is created for you when you
          buy or when you are invited; you choose a password to use it.
        </p>
        <p>
          <strong>At the event:</strong> the time your ticket was scanned at the door, and the
          drinks you redeem with your tokens.
        </p>
        <p>
          <strong>If you upload photos or videos</strong> from an event, we keep the file, who
          uploaded it and when.
        </p>
        <p>
          <strong>If you subscribe to the newsletter:</strong> your email address, until you
          unsubscribe.
        </p>
        <p>
          We keep this data for as long as you have an account or tickets with us, and afterwards
          for as long as the law requires for accounting.
        </p>
      </LegalSection>

      <LegalSection heading="Where it is kept, and who helps us">
        <p>
          Our database is hosted by Supabase in Ireland, and the application runs on Vercel, in
          Dublin. Payments are processed by SumUp. Emails are sent through Resend. We measure how
          the site is used with PostHog, on servers in the EU, from our own server and without any
          tracking script or cookie in your browser. If you add a ticket to Apple Wallet, the pass
          is generated by us and stored on your device.
        </p>
        <p>
          These services process your data on our behalf and under contract. We do not sell your
          data and we do not share it with anyone else.
        </p>
      </LegalSection>

      <LegalSection heading="Cookies">
        <p>
          We use only the cookies needed to keep you signed in. There are no advertising or
          tracking cookies, which is why there is no cookie banner.
        </p>
      </LegalSection>

      <LegalSection heading="Photos and video at events">
        <p>
          Events are photographed and filmed, and the material may be published in recaps, after
          movies, the gallery and social media. We do this in our legitimate interest to tell what
          re:sonate is. If you appear in a published image and want it removed, write to{" "}
          <a href={`mailto:${LEGAL_CONTACT}`} className="inline-flex min-h-11 items-center text-accent">{LEGAL_CONTACT}</a>: we will
          remove it from everything we control.
        </p>
      </LegalSection>

      <LegalSection heading="Your rights">
        <p>
          You can ask us what we hold about you, ask us to correct it, ask for a copy, or ask us to
          delete your account and its data. Write to{" "}
          <a href={`mailto:${LEGAL_CONTACT}`} className="inline-flex min-h-11 items-center text-accent">{LEGAL_CONTACT}</a> from the
          address on your account. Deleting an account removes your profile; tickets already used
          and payment records we must keep for accounting are retained for the period the law
          requires.
        </p>
        <p>
          You can also complain to the Italian data protection authority (Garante per la
          protezione dei dati personali).
        </p>
      </LegalSection>
    </LegalBody>
    </PageShell>
    </div>
    <AppNav
      role={role as UserRole | null}
      capabilities={[...capabilities]}
      liveAssignmentCapabilities={
        liveAssignmentCapabilities ? [...liveAssignmentCapabilities] : null
      }
    />
    </>
  );
}
